name: Build and Release Flutter APK

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  workflow_dispatch:  # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java JDK
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.0'  # Use your Flutter version
        channel: 'stable'
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Run tests (optional)
      run: flutter test
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Build App Bundle (optional)
      run: flutter build appbundle --release
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/app/outputs/flutter-apk/app-release.apk
          build/app/outputs/bundle/release/app-release.aab
        body: |
          ## What's Changed
          - Add your release notes here
          
          ## Download
          - **APK**: Direct install on Android devices
          - **AAB**: For Google Play Store (if included)
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload APK as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
    - name: Upload AAB as Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-aab
        path: build/app/outputs/bundle/release/app-release.aab
